CREATE DATABASE ADONET
USE ADONET

CREATE TABLE Students(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(25),
Surname VARCHAR(25),
Age INT CHECK(Age BETWEEN 10 AND 65)
)
INSERT INTO Students VALUES ('Nurana', 'Valiyeva',19)